import {z} from 'zod';
export const dictionaryInputSchema = z.object({text: z.string().min(1).max(1600), source_language: z.enum(['en', 'zh']), target_language: z.enum(['en', 'zh', 'vi']), context: z.string().min(1).max(2400)}).strict();
export const dictionaryResultSchema = z.object({available: z.boolean(), source_language: z.string(), target_language: z.string(), selected_text: z.string(), summary: z.string().optional(), natural_translation: z.string().optional(), grammar_notes: z.array(z.string()).optional(), vocabulary: z.array(z.object({fragment: z.string(), meaning: z.string(), pos: z.string(), pronunciation: z.string()}).passthrough()).optional(), usage_note: z.string().optional(), claim: z.string()}).passthrough();
export type DictionaryInput = z.infer<typeof dictionaryInputSchema>; export type DictionaryResult = z.infer<typeof dictionaryResultSchema>;
export const libraryItemSchema = z.object({word: z.string().min(1), phonetic: z.string(), part_of_speech: z.string(), definition: z.string(), translation_vi: z.string(), added_at: z.string(), source_essay_id: z.number().nullable().optional(), source_fragment: z.string(), source_kind: z.string(), focus_note: z.string(), review_stage: z.number(), stage_label: z.string(), successful_recalls: z.number(), lapse_count: z.number(), last_reviewed_at: z.string(), next_review_at: z.string(), due: z.boolean()}).passthrough();
export const librarySchema = z.object({items: z.array(libraryItemSchema), summary: z.object({total: z.number(), due: z.number(), available: z.number()})}).strict();
export const saveLibraryInputSchema = z.object({word: z.string().min(1).max(180), phonetic: z.string().max(180), part_of_speech: z.string().max(120), definition: z.string().max(2400), translation_vi: z.string().max(2400), source_essay_id: z.number().int().positive().optional(), source_fragment: z.string().max(1200), source_kind: z.enum(['manual', 'dictionary', 'feedback', 'strength']), focus_note: z.string().max(2400)}).strict();
export const saveLibraryResultSchema = z.object({saved: z.literal(true), item: libraryItemSchema}).strict();
export type SaveLibraryVocabularyInput = z.infer<typeof saveLibraryInputSchema>;
