import React from 'react';
import renderer, {act} from 'react-test-renderer';
import {I18nProvider} from '../../src/i18n/I18nProvider';
import {ThemeProvider} from '../../src/theme/ThemeProvider';
import GrammarScreen from '../../app/(app)/grammar';
import LibraryScreen from '../../app/(app)/library';
import JourneyScreen from '../../app/(app)/journey';
import ProfileScreen from '../../app/(app)/profile';

const mockPush = jest.fn();
let mockCookie: string | null = 'cookie';
const mockGrammarPractice = {isPending: false, isError: false, mutate: jest.fn()};
const mockGrammarComplete = {isPending: false, isError: false, mutate: jest.fn()};
const mockGrammarLibrary = {isPending: false, isError: false, data: {lessons: [{id: 'en-articles', title: 'Articles', level: 'B1', completed: false}], total: 1, completed: 0, levels: ['B1'], level_names: {B1: 'B1'}, language: 'en'}};
const mockGrammarLesson = {isPending: false, isError: false, data: {id: 'en-articles', title: 'Articles', level: 'B1', completed: false, examples: [{target: 'A learner writes.'}], quick_reference: {rule: 'Use a.'}}};
const mockLibraryQuery = {isPending: false, isLoading: false, isError: false, data: {items: [{word: 'clarity', phonetic: '', part_of_speech: 'noun', definition: 'clear expression', translation_vi: '', added_at: '2026-01-01', source_fragment: '', source_kind: 'manual', focus_note: '', review_stage: 1, stage_label: 'Learning', successful_recalls: 0, lapse_count: 0, last_reviewed_at: '', next_review_at: '', due: true}], summary: {total: 1, due: 1, available: 0}}};
const mockReview = {isPending: false, isError: false, mutate: jest.fn()};
const mockDashboard = {isPending: false, isError: false, data: {essay_count: 2, revision_count: 3, skill_score: 82, cefr: 'B2', streak: 1, recent_average: 80, trend: [], metrics: {}, error_counts: {}, error_memory: [{category: 'grammar'}], next_level: null, version: '2.17.3'}};
const mockOutcomes = {isPending: false, isError: false, data: {items: [{essay_id: 1, series_id: 1, revision_no: 1, created_at: '2026-01-01', overall: 82, status: 'improved', intent: 'repair', focus_family: 'grammar', focus_category: 'grammar', focus_label: 'Articles', grammar_id: '', grammar_title: '', issue_count: 0, previous_issue_count: 1, strength_count: 1, error_evidence: [], strength_evidence: [], practice: {}}], latest: null}};
const mockMemory = {isPending: false, isError: false, data: undefined};
const mockProfile = {isPending: false, isError: false, data: {exists: true, language: 'en', goal: 'everyday', style: 'guided', pinyin: 'auto', native_language: 'vi', theme_preset: 'editorial', updated_at: '2026-01-01'}};
const mockSaveProfile = {isPending: false, isError: false, mutateAsync: jest.fn(() => Promise.resolve({}))};
const mockSetLanguage = {isPending: false, isError: false, mutateAsync: jest.fn(() => Promise.resolve({ok: true, active: 'zh'}))};
const mockProduct = {isPending: false, isError: false, data: {available: true, plan: {id: 'free', name: 'Free', description: 'Core writing practice.', price_label: 'Free'}, subscription: {state: 'active', status: 'active'}, plan_state: 'active', billing_ready: false, features: {}}};

jest.mock('expo-router', () => ({useRouter: () => ({push: mockPush, replace: jest.fn()})}));
jest.mock('../../src/auth/SessionHarness', () => ({useSession: () => ({sessionCookie: mockCookie, session: {status: mockCookie ? 'authenticated' : 'signed_out'}})}));
jest.mock('../../src/api/client', () => ({createConfiguredApiClient: () => ({}), ApiClient: class {}}));
jest.mock('../../src/query/useGrammar', () => ({useGrammarLibrary: () => mockGrammarLibrary, useGrammarLesson: () => mockGrammarLesson, useCompleteGrammarLesson: () => mockGrammarComplete}));
jest.mock('../../src/query/useWritingEvaluation', () => ({useGrammarPractice: () => mockGrammarPractice}));
jest.mock('../../src/query/useReadingLibrary', () => ({useLibraryVocabulary: () => mockLibraryQuery, useReviewLibraryVocabulary: () => mockReview}));
jest.mock('../../src/query/useJourney', () => ({useJourneyDashboard: () => mockDashboard, useJourneyOutcomes: () => mockOutcomes}));
jest.mock('../../src/query/useHome', () => ({useLearningMemory: () => mockMemory, useEssays: () => mockMemory, useReadingSessionHistory: () => mockMemory}));
jest.mock('../../src/query/useLearnerProfile', () => ({useLearnerProfile: () => mockProfile, useSaveLearnerProfile: () => mockSaveProfile, useSetLearningLanguage: () => mockSetLanguage}));
jest.mock('../../src/query/useProductMe', () => ({useProductMe: () => mockProduct}));

const render = (screen: React.ReactNode, locale: 'en' | 'zh' = 'en') => renderer.create(<I18nProvider initialLocale={locale}><ThemeProvider>{screen}</ThemeProvider></I18nProvider>);
const grammarTask = {grammar_id: 'en-articles', title: 'Articles', level: 'B1', target_level: 'B1', prompt: 'Write three sentences.', practice_blueprint: {}, practice_context: {intent: 'repair', focus_category: 'grammar', focus_label: 'Articles', focus_family: 'grammar', task_type: 'story', topic: 'grammar transfer', target_level: 'B1', action_label: 'Practice this grammar', reason: 'A writing finding', evidence: '', focus_instruction: 'Use articles.', grammar_id: 'en-articles', grammar_title: 'Articles'}, source: 'static-grammar-kb'};

describe('R20-6 native learner loop', () => {
  beforeEach(() => { mockCookie = 'cookie'; mockPush.mockReset(); mockGrammarPractice.mutate.mockReset(); mockGrammarComplete.mutate.mockReset(); mockReview.mutate.mockReset(); mockSaveProfile.mutateAsync.mockReset(); mockSaveProfile.mutateAsync.mockResolvedValue({}); mockSetLanguage.mutateAsync.mockReset(); mockSetLanguage.mutateAsync.mockResolvedValue({ok: true, active: 'zh'}); mockGrammarLibrary.isPending = false; mockGrammarLibrary.isError = false; mockGrammarLesson.isPending = false; mockGrammarLesson.isError = false; mockLibraryQuery.isLoading = false; mockLibraryQuery.isError = false; mockLibraryQuery.data = {items: [{word: 'clarity', phonetic: '', part_of_speech: 'noun', definition: 'clear expression', translation_vi: '', added_at: '2026-01-01', source_fragment: '', source_kind: 'manual', focus_note: '', review_stage: 1, stage_label: 'Learning', successful_recalls: 0, lapse_count: 0, last_reviewed_at: '', next_review_at: '', due: true}], summary: {total: 1, due: 1, available: 0}}; mockDashboard.isPending = false; mockDashboard.isError = false; mockOutcomes.isPending = false; mockOutcomes.isError = false; mockProfile.isPending = false; mockProfile.isError = false; });
  // The overview's first action opens the next lesson (matching grammar.js's
  // "Continue curriculum" CTA, which only opens the lesson); the write-transfer
  // handoff itself lives on the opened lesson's rail, as it does on the web.
  it.each(['en', 'zh'] as const)('hands canonical Grammar practice into Writing in %s', (locale) => { const view = render(<GrammarScreen />, locale); const openLesson = view.root.findAll((node) => node.props.accessibilityRole === 'button')[0]; act(() => openLesson?.props.onPress()); const writeButton = view.root.findAll((node) => node.props.accessibilityRole === 'button' && node.props.accessibilityLabel === (locale === 'zh' ? '在 Writing 中使用' : 'Use this in Writing'))[0]; act(() => writeButton?.props.onPress()); expect(mockGrammarPractice.mutate).toHaveBeenCalledWith({grammarId: 'en-articles', evidence: ''}, expect.any(Object)); act(() => mockGrammarPractice.mutate.mock.calls[0][1].onSuccess(grammarTask)); expect(mockPush).toHaveBeenCalledWith('/(app)/writing'); });
  it.each(['en', 'zh'] as const)('requires reveal before due-word recall actions in %s', (locale) => { const view = render(<LibraryScreen />, locale); expect(view.root.findAll((node) => node.props.children === 'clear expression')).toHaveLength(0); expect(view.root.findAll((node) => node.props.children === (locale === 'zh' ? '再来一次' : 'Again'))).toHaveLength(0); const reveal = view.root.findAll((node) => node.props.accessibilityRole === 'button' && node.props.accessibilityLabel === (locale === 'zh' ? '显示释义' : 'Reveal meaning'))[0]; act(() => reveal?.props.onPress()); expect(view.root.findAll((node) => node.props.children === 'clear expression')).not.toHaveLength(0); const gotIt = view.root.findAll((node) => node.props.accessibilityLabel === (locale === 'zh' ? '记住了' : 'Got it'))[0]; act(() => gotIt?.props.onPress()); expect(mockReview.mutate).toHaveBeenCalledWith({word: 'clarity', result: 'got_it'}, expect.any(Object)); });
  it('keeps empty, unavailable, and signed-out states truthful', () => { mockLibraryQuery.data = {items: [], summary: {total: 0, due: 0, available: 0}}; let view = render(<LibraryScreen />, 'en'); expect(view.root.findAll((node) => String(node.props.children).includes('No saved words yet.'))).not.toHaveLength(0); mockLibraryQuery.isError = true; view = render(<LibraryScreen />, 'zh'); expect(view.root.findByProps({accessibilityRole: 'alert'})).toBeDefined(); mockCookie = null; view = render(<JourneyScreen />, 'en'); expect(view.root.findAll((node) => node.props.children === 'Sign in to view your learning journey.')).not.toHaveLength(0); expect(view.root.findAll((node) => node.props.accessibilityRole === 'alert')).toHaveLength(0); });
  it('shows Journey loading while the initial progress fetch is pending', () => { mockDashboard.isPending = true; (mockDashboard as {data: unknown}).data = undefined; mockOutcomes.isPending = true; (mockOutcomes as {data: unknown}).data = undefined; const view = render(<JourneyScreen />, 'en'); expect(view.root.findAll((node) => node.props.children === 'Loading your progress…')).not.toHaveLength(0); mockDashboard.isPending = false; mockDashboard.data = {essay_count: 2, revision_count: 3, skill_score: 82, cefr: 'B2', streak: 1, recent_average: 80, trend: [], metrics: {}, error_counts: {}, error_memory: [{category: 'grammar'}], next_level: null, version: '2.17.3'}; mockOutcomes.isPending = false; mockOutcomes.data = {items: [{essay_id: 1, series_id: 1, revision_no: 1, created_at: '2026-01-01', overall: 82, status: 'improved', intent: 'repair', focus_family: 'grammar', focus_category: 'grammar', focus_label: 'Articles', grammar_id: '', grammar_title: '', issue_count: 0, previous_issue_count: 1, strength_count: 1, error_evidence: [], strength_evidence: [], practice: {}}], latest: null}; });
  it('keeps disabled signed-out queries unavailable even when React Query reports pending', () => { mockCookie = null; mockDashboard.isPending = true; mockOutcomes.isPending = true; const view = render(<JourneyScreen />, 'en'); expect(view.root.findAll((node) => node.props.children === 'Sign in to view your learning journey.')).not.toHaveLength(0); expect(view.root.findAll((node) => node.props.accessibilityRole === 'alert')).toHaveLength(0); expect(view.root.findAll((node) => node.props.children === 'Loading your progress…')).toHaveLength(0); });
  it.each(['en', 'zh'] as const)('renders authoritative Journey progress in %s', (locale) => { const view = render(<JourneyScreen />, locale); expect(view.root.findAll((node) => String(node.props.children).includes(locale === 'zh' ? '写作篇数' : 'Writing pieces'))).not.toHaveLength(0); });
  it('saves authorized profile settings and language changes', async () => { const view = render(<ProfileScreen />); const saveButton = view.root.findAll((node) => node.props.accessibilityRole === 'button' && node.props.accessibilityLabel === 'Save profile')[0]; await act(async () => { saveButton?.props.onPress(); await Promise.resolve(); }); expect(mockSaveProfile.mutateAsync).toHaveBeenCalled(); const learningLanguage = view.root.findAll((node) => node.props.accessibilityLabel === 'Learning language: Chinese')[0]; act(() => learningLanguage?.props.onPress()); expect(mockSetLanguage.mutateAsync).toHaveBeenCalledWith('zh'); });
  it('reports profile mutation failure without claiming a save', async () => { mockSaveProfile.mutateAsync.mockRejectedValueOnce(new Error('offline')); const view = render(<ProfileScreen />); const saveButton = view.root.findAll((node) => node.props.accessibilityRole === 'button' && node.props.accessibilityLabel === 'Save profile')[0]; await act(async () => { saveButton?.props.onPress(); await Promise.resolve(); await Promise.resolve(); }); expect(view.root.findByProps({accessibilityRole: 'alert'})).toBeDefined(); });
});
