# AI Writing Coach Grammar Course
# Original CEFR-aligned syllabus. This is not an official CEFR textbook.
GRAMMAR_COURSE = [{'id': 'a1-verb-be-am-is-are',
  'order': 1,
  'level': 'A1',
  'category': 'Core sentence',
  'title': 'Verb be: am, is, are',
  'objective_vi': 'Dùng be để mô tả danh tính, trạng thái và đặc điểm.'},
 {'id': 'a1-subject-pronouns-and-object-pronouns',
  'order': 2,
  'level': 'A1',
  'category': 'Core sentence',
  'title': 'Subject pronouns and object pronouns',
  'objective_vi': 'Phân biệt I/me, he/him, they/them trong câu.'},
 {'id': 'a1-possessive-adjectives-and-pronouns',
  'order': 3,
  'level': 'A1',
  'category': 'Possession',
  'title': 'Possessive adjectives and pronouns',
  'objective_vi': 'Dùng my/mine, your/yours, his/her/theirs đúng vị trí.'},
 {'id': 'a1-have-and-have-got',
  'order': 4,
  'level': 'A1',
  'category': 'Core verbs',
  'title': 'Have and have got',
  'objective_vi': 'Nói về sở hữu, quan hệ và đặc điểm cơ bản.'},
 {'id': 'a1-present-simple',
  'order': 5,
  'level': 'A1',
  'category': 'Tenses',
  'title': 'Present simple',
  'objective_vi': 'Diễn tả thói quen, sự thật và lịch trình.'},
 {'id': 'a1-adverbs-of-frequency',
  'order': 6,
  'level': 'A1',
  'category': 'Frequency',
  'title': 'Adverbs of frequency',
  'objective_vi': 'Đặt always, usually, often, sometimes, never đúng vị trí.'},
 {'id': 'a1-present-continuous',
  'order': 7,
  'level': 'A1',
  'category': 'Tenses',
  'title': 'Present continuous',
  'objective_vi': 'Nói về hành động đang diễn ra hoặc tình huống tạm thời.'},
 {'id': 'a1-there-is-and-there-are',
  'order': 8,
  'level': 'A1',
  'category': 'Existence',
  'title': 'There is and there are',
  'objective_vi': 'Mô tả sự tồn tại của người hoặc vật.'},
 {'id': 'a1-a-an-and-the',
  'order': 9,
  'level': 'A1',
  'category': 'Articles',
  'title': 'A, an and the',
  'objective_vi': 'Dùng mạo từ với danh từ đếm được số ít và reference cụ thể.'},
 {'id': 'a1-plural-nouns',
  'order': 10,
  'level': 'A1',
  'category': 'Nouns',
  'title': 'Plural nouns',
  'objective_vi': 'Tạo số nhiều thường và bất quy tắc phổ biến.'},
 {'id': 'a1-some-any-much-and-many',
  'order': 11,
  'level': 'A1',
  'category': 'Quantity',
  'title': 'Some, any, much and many',
  'objective_vi': 'Dùng lượng từ cơ bản với danh từ đếm được và không đếm được.'},
 {'id': 'a1-basic-question-forms',
  'order': 12,
  'level': 'A1',
  'category': 'Questions',
  'title': 'Basic question forms',
  'objective_vi': 'Tạo câu hỏi với be, do/does và từ để hỏi.'},
 {'id': 'a2-past-simple',
  'order': 13,
  'level': 'A2',
  'category': 'Tenses',
  'title': 'Past simple',
  'objective_vi': 'Kể sự kiện đã kết thúc trong quá khứ.'},
 {'id': 'a2-past-continuous',
  'order': 14,
  'level': 'A2',
  'category': 'Tenses',
  'title': 'Past continuous',
  'objective_vi': 'Mô tả background hoặc hành động đang diễn ra trong quá khứ.'},
 {'id': 'a2-present-perfect-introduction',
  'order': 15,
  'level': 'A2',
  'category': 'Tenses',
  'title': 'Present perfect: introduction',
  'objective_vi': 'Nói về trải nghiệm và kết quả liên quan đến hiện tại.'},
 {'id': 'a2-going-to',
  'order': 16,
  'level': 'A2',
  'category': 'Future',
  'title': 'Going to',
  'objective_vi': 'Nói về kế hoạch và dự đoán dựa trên dấu hiệu hiện tại.'},
 {'id': 'a2-will-and-won-t',
  'order': 17,
  'level': 'A2',
  'category': 'Future',
  'title': "Will and won't",
  'objective_vi': 'Dùng will cho quyết định tức thời, lời hứa và dự đoán.'},
 {'id': 'a2-comparatives',
  'order': 18,
  'level': 'A2',
  'category': 'Comparison',
  'title': 'Comparatives',
  'objective_vi': 'So sánh hai đối tượng rõ ràng và tự nhiên.'},
 {'id': 'a2-superlatives',
  'order': 19,
  'level': 'A2',
  'category': 'Comparison',
  'title': 'Superlatives',
  'objective_vi': 'Nói về đối tượng nổi bật nhất trong một nhóm.'},
 {'id': 'a2-adjectives-and-adverbs',
  'order': 20,
  'level': 'A2',
  'category': 'Adjectives',
  'title': 'Adjectives and adverbs',
  'objective_vi': 'Phân biệt từ mô tả danh từ và cách hành động.'},
 {'id': 'a2-should-must-and-have-to',
  'order': 21,
  'level': 'A2',
  'category': 'Modals',
  'title': 'Should, must and have to',
  'objective_vi': 'Đưa lời khuyên và diễn tả nghĩa vụ.'},
 {'id': 'a2-gerunds-and-infinitives-basics',
  'order': 22,
  'level': 'A2',
  'category': 'Verb patterns',
  'title': 'Gerunds and infinitives: basics',
  'objective_vi': 'Làm quen với verb + V-ing và verb + to V.'},
 {'id': 'a2-who-which-and-that',
  'order': 23,
  'level': 'A2',
  'category': 'Relative clauses',
  'title': 'Who, which and that',
  'objective_vi': 'Nối thông tin để giảm câu ngắn rời rạc.'},
 {'id': 'a2-zero-and-first-conditionals',
  'order': 24,
  'level': 'A2',
  'category': 'Conditionals',
  'title': 'Zero and first conditionals',
  'objective_vi': 'Nói về quy luật và khả năng tương lai.'},
 {'id': 'b1-present-perfect-vs-past-simple',
  'order': 25,
  'level': 'B1',
  'category': 'Tenses',
  'title': 'Present perfect vs past simple',
  'objective_vi': 'Chọn đúng giữa liên hệ hiện tại và mốc quá khứ đã kết thúc.'},
 {'id': 'b1-present-perfect-continuous',
  'order': 26,
  'level': 'B1',
  'category': 'Tenses',
  'title': 'Present perfect continuous',
  'objective_vi': 'Nhấn mạnh một quá trình kéo dài đến hiện tại.'},
 {'id': 'b1-past-perfect',
  'order': 27,
  'level': 'B1',
  'category': 'Tenses',
  'title': 'Past perfect',
  'objective_vi': 'Làm rõ sự kiện nào xảy ra trước trong quá khứ.'},
 {'id': 'b1-future-forms-in-context',
  'order': 28,
  'level': 'B1',
  'category': 'Future',
  'title': 'Future forms in context',
  'objective_vi': 'Phân biệt will, going to và present continuous theo ngữ cảnh.'},
 {'id': 'b1-modals-of-possibility-and-deduction',
  'order': 29,
  'level': 'B1',
  'category': 'Modals',
  'title': 'Modals of possibility and deduction',
  'objective_vi': "Dùng may, might, could, must, can't để thể hiện mức chắc chắn."},
 {'id': 'b1-second-conditional',
  'order': 30,
  'level': 'B1',
  'category': 'Conditionals',
  'title': 'Second conditional',
  'objective_vi': 'Nói về giả định hiện tại hoặc tương lai ít thực tế.'},
 {'id': 'b1-used-to-and-would',
  'order': 31,
  'level': 'B1',
  'category': 'Past habits',
  'title': 'Used to and would',
  'objective_vi': 'Mô tả thói quen hoặc trạng thái trong quá khứ đã thay đổi.'},
 {'id': 'b1-passive-voice-basics',
  'order': 32,
  'level': 'B1',
  'category': 'Voice',
  'title': 'Passive voice: basics',
  'objective_vi': 'Chuyển trọng tâm từ người thực hiện sang hành động hoặc kết quả.'},
 {'id': 'b1-reported-statements',
  'order': 33,
  'level': 'B1',
  'category': 'Reported speech',
  'title': 'Reported statements',
  'objective_vi': 'Tường thuật lời nói với tense và đại từ phù hợp.'},
 {'id': 'b1-defining-and-non-defining-clauses',
  'order': 34,
  'level': 'B1',
  'category': 'Relative clauses',
  'title': 'Defining and non-defining clauses',
  'objective_vi': 'Phân biệt thông tin thiết yếu và thông tin bổ sung.'},
 {'id': 'b1-articles-beyond-the-basics',
  'order': 35,
  'level': 'B1',
  'category': 'Articles',
  'title': 'Articles beyond the basics',
  'objective_vi': 'Dùng the và zero article với khái niệm, nơi chốn và reference.'},
 {'id': 'b1-linking-contrast-reason-and-result',
  'order': 36,
  'level': 'B1',
  'category': 'Coherence',
  'title': 'Linking contrast, reason and result',
  'objective_vi': 'Nối ý bằng although, however, therefore, as a result, because.'},
 {'id': 'b2-third-conditional',
  'order': 37,
  'level': 'B2',
  'category': 'Conditionals',
  'title': 'Third conditional',
  'objective_vi': 'Phân tích kết quả giả định trong quá khứ.'},
 {'id': 'b2-mixed-conditionals',
  'order': 38,
  'level': 'B2',
  'category': 'Conditionals',
  'title': 'Mixed conditionals',
  'objective_vi': 'Kết nối nguyên nhân quá khứ với kết quả hiện tại hoặc ngược lại.'},
 {'id': 'b2-wish-and-if-only',
  'order': 39,
  'level': 'B2',
  'category': 'Unreal language',
  'title': 'Wish and if only',
  'objective_vi': 'Diễn tả mong muốn, tiếc nuối và phàn nàn.'},
 {'id': 'b2-past-modals-for-speculation',
  'order': 40,
  'level': 'B2',
  'category': 'Modals',
  'title': 'Past modals for speculation',
  'objective_vi': 'Suy đoán và đánh giá hành động trong quá khứ.'},
 {'id': 'b2-advanced-passive-forms',
  'order': 41,
  'level': 'B2',
  'category': 'Voice',
  'title': 'Advanced passive forms',
  'objective_vi': 'Dùng passive với modal, perfect và continuous.'},
 {'id': 'b2-have-get-something-done',
  'order': 42,
  'level': 'B2',
  'category': 'Causative',
  'title': 'Have/get something done',
  'objective_vi': 'Nói về việc nhờ hoặc thuê người khác làm việc.'},
 {'id': 'b2-participle-clauses',
  'order': 43,
  'level': 'B2',
  'category': 'Advanced sentences',
  'title': 'Participle clauses',
  'objective_vi': 'Rút gọn mệnh đề bằng V-ing hoặc V-ed để viết gọn hơn.'},
 {'id': 'b2-reduced-relative-clauses',
  'order': 44,
  'level': 'B2',
  'category': 'Relative clauses',
  'title': 'Reduced relative clauses',
  'objective_vi': 'Rút gọn relative clause khi cấu trúc cho phép.'},
 {'id': 'b2-introductory-inversion',
  'order': 45,
  'level': 'B2',
  'category': 'Emphasis',
  'title': 'Introductory inversion',
  'objective_vi': 'Dùng đảo ngữ với một số negative adverbials.'},
 {'id': 'b2-cleft-sentences',
  'order': 46,
  'level': 'B2',
  'category': 'Emphasis',
  'title': 'Cleft sentences',
  'objective_vi': 'Dùng It is...that và What...is để kiểm soát trọng tâm.'},
 {'id': 'b2-advanced-reporting-patterns',
  'order': 47,
  'level': 'B2',
  'category': 'Reported speech',
  'title': 'Advanced reporting patterns',
  'objective_vi': 'Dùng reporting verbs và verb patterns linh hoạt.'},
 {'id': 'b2-reference-and-substitution',
  'order': 48,
  'level': 'B2',
  'category': 'Coherence',
  'title': 'Reference and substitution',
  'objective_vi': 'Tránh lặp bằng this/that/one/ones/do so và reference rõ.'},
 {'id': 'c1-advanced-simple-and-continuous-aspect',
  'order': 49,
  'level': 'C1',
  'category': 'Aspect',
  'title': 'Advanced simple and continuous aspect',
  'objective_vi': 'Tinh chỉnh simple/continuous để thể hiện trạng thái, xu hướng và góc nhìn.'},
 {'id': 'c1-advanced-perfect-aspect',
  'order': 50,
  'level': 'C1',
  'category': 'Aspect',
  'title': 'Advanced perfect aspect',
  'objective_vi': 'Dùng perfect để liên kết thời điểm và nhấn mạnh trước/sau chính xác.'},
 {'id': 'c1-negative-adverbial-inversion',
  'order': 51,
  'level': 'C1',
  'category': 'Emphasis',
  'title': 'Negative adverbial inversion',
  'objective_vi': 'Đảo ngữ với hardly, scarcely, no sooner, under no circumstances.'},
 {'id': 'c1-fronting-for-emphasis',
  'order': 52,
  'level': 'C1',
  'category': 'Information structure',
  'title': 'Fronting for emphasis',
  'objective_vi': 'Đưa thành phần quan trọng lên đầu câu để tạo trọng tâm có kiểm soát.'},
 {'id': 'c1-reporting-passives',
  'order': 53,
  'level': 'C1',
  'category': 'Voice',
  'title': 'Reporting passives',
  'objective_vi': 'Dùng It is believed... / He is said to... trong formal writing.'},
 {'id': 'c1-nominalisation',
  'order': 54,
  'level': 'C1',
  'category': 'Formal style',
  'title': 'Nominalisation',
  'objective_vi': 'Chuyển verb/adjective thành noun khi cần văn phong formal và cô đọng.'},
 {'id': 'c1-mandative-subjunctive',
  'order': 55,
  'level': 'C1',
  'category': 'Formal grammar',
  'title': 'Mandative subjunctive',
  'objective_vi': 'Dùng suggest/recommend/essential + that + base verb trong formal grammar.'},
 {'id': 'c1-nuanced-modal-meaning',
  'order': 56,
  'level': 'C1',
  'category': 'Modality',
  'title': 'Nuanced modal meaning',
  'objective_vi': 'Phân biệt certainty, politeness và stance bằng modal và semi-modal.'},
 {'id': 'c1-advanced-linking-and-concession',
  'order': 57,
  'level': 'C1',
  'category': 'Cohesion',
  'title': 'Advanced linking and concession',
  'objective_vi': 'Dùng linker nâng cao đúng quan hệ logic và register.'},
 {'id': 'c1-ellipsis-and-substitution',
  'order': 58,
  'level': 'C1',
  'category': 'Cohesion',
  'title': 'Ellipsis and substitution',
  'objective_vi': 'Lược bỏ phần lặp và thay thế thông tin mà vẫn giữ clarity.'},
 {'id': 'c1-hedging-and-cautious-claims',
  'order': 59,
  'level': 'C1',
  'category': 'Academic style',
  'title': 'Hedging and cautious claims',
  'objective_vi': 'Giới hạn mức chắc chắn để lập luận chính xác hơn.'},
 {'id': 'c1-sentence-rhythm-and-information-flow',
  'order': 60,
  'level': 'C1',
  'category': 'Style',
  'title': 'Sentence rhythm and information flow',
  'objective_vi': 'Sắp xếp old-to-new information và độ dài câu để đoạn văn dễ đọc.'},
 {'id': 'c2-advanced-tense-and-aspect-viewpoint',
  'level': 'C2',
  'category': 'Aspect',
  'title': 'Advanced tense and aspect viewpoint',
  'objective_vi': 'Điều khiển tense và aspect theo góc nhìn, trọng tâm và mạch thời gian phức tạp thay vì chỉ theo dấu '
                  'hiệu thời gian.',
  'order': 61},
 {'id': 'c2-conditional-inversion-and-compression',
  'level': 'C2',
  'category': 'Conditionals',
  'title': 'Conditional inversion and compression',
  'objective_vi': 'Dùng Had I..., Were I..., Should you... và các dạng rút gọn điều kiện một cách tự nhiên trong văn '
                  'phong phù hợp.',
  'order': 62},
 {'id': 'c2-complex-clause-embedding',
  'level': 'C2',
  'category': 'Complex clauses',
  'title': 'Complex clause embedding',
  'objective_vi': 'Kiểm soát noun clauses, embedded questions và nhiều tầng mệnh đề mà vẫn giữ câu rõ và dễ theo dõi.',
  'order': 63},
 {'id': 'c2-nominal-relative-clauses',
  'level': 'C2',
  'category': 'Relative clauses',
  'title': 'Nominal relative clauses',
  'objective_vi': 'Dùng what, whatever, whoever, whichever như một thành phần danh từ để viết cô đọng và linh hoạt.',
  'order': 64},
 {'id': 'c2-concession-and-counterargument',
  'level': 'C2',
  'category': 'Concession',
  'title': 'Nuanced concession and counterargument',
  'objective_vi': 'Diễn đạt nhượng bộ và phản biện bằng các cấu trúc concession linh hoạt nhưng vẫn đúng register.',
  'order': 65},
 {'id': 'c2-modality-and-authorial-stance',
  'level': 'C2',
  'category': 'Modality',
  'title': 'Modality and authorial stance',
  'objective_vi': 'Điều chỉnh mức chắc chắn, khoảng cách và thái độ của người viết bằng modal, lexical stance và cấu '
                  'trúc đánh giá.',
  'order': 66},
 {'id': 'c2-information-packaging-and-end-weight',
  'level': 'C2',
  'category': 'Information structure',
  'title': 'Information packaging and end-weight',
  'objective_vi': 'Sắp xếp thông tin cũ-mới, extraposition và end-weight để câu dài vẫn tự nhiên và dễ xử lý.',
  'order': 67},
 {'id': 'c2-advanced-reporting-and-distancing',
  'level': 'C2',
  'category': 'Reporting',
  'title': 'Advanced reporting and distancing',
  'objective_vi': 'Kết hợp reporting verbs, passive reporting, perfect infinitives và distancing language để tường '
                  'thuật chính xác.',
  'order': 68},
 {'id': 'c2-negation-quantifiers-and-scope',
  'level': 'C2',
  'category': 'Meaning and scope',
  'title': 'Negation, quantifiers and scope',
  'objective_vi': 'Tránh ambiguity khi not, all, every, only, hardly và quantifiers có thể tạo nhiều cách hiểu.',
  'order': 69},
 {'id': 'c2-ellipsis-substitution-and-reference',
  'level': 'C2',
  'category': 'Cohesion',
  'title': 'Advanced ellipsis, substitution and reference',
  'objective_vi': 'Giảm lặp ở cấp câu và đoạn bằng ellipsis, substitution và reference nhưng không làm người đọc mất '
                  'antecedent.',
  'order': 70},
 {'id': 'c2-register-driven-grammar',
  'level': 'C2',
  'category': 'Register',
  'title': 'Register-driven grammar choices',
  'objective_vi': 'Chọn cấu trúc ngữ pháp theo email, review, argument, report hoặc academic style thay vì dùng cùng '
                  'một register cho mọi bài.',
  'order': 71},
 {'id': 'c2-syntactic-variety-and-editing',
  'level': 'C2',
  'category': 'Editing',
  'title': 'Syntactic variety and precision editing',
  'objective_vi': 'Biên tập câu ở cấp độ cao: giảm dư thừa, phá nhịp câu đơn điệu và chọn độ phức tạp vừa đủ cho ý '
                  'nghĩa.',
  'order': 72}]
GRAMMAR_BY_ID = {x["id"]: x for x in GRAMMAR_COURSE}
