import {useMutation, useQuery, useQueryClient, type UseMutationResult, type UseQueryResult} from '@tanstack/react-query';
import {ApiClient} from '../api/client';
import type {DictionaryInput, DictionaryResult} from '../api/contracts/library';
import type {ReadingAnswerResult, ReadingGenerateInput, ReadingSession} from '../api/contracts/reading';
import {ApiError} from '../api/errors';
const enabled = (client: ApiClient | null, cookie?: string | null) => Boolean(client && typeof cookie === 'string' && cookie.length > 0);
export function useCreateReadingSession(client: ApiClient | null, cookie?: string | null): UseMutationResult<ReadingSession, ApiError, ReadingGenerateInput> { return useMutation({mutationFn: (input) => client ? client.createReadingSession(input, {sessionCookie: cookie ?? undefined}) : Promise.reject(new ApiError('configuration_missing', 'API client is unavailable')), retry: false}); }
export function useOpenReadingSession(client: ApiClient | null, cookie?: string | null): UseMutationResult<ReadingSession, ApiError, number> { return useMutation({mutationFn: (id) => client ? client.getReadingSession(id, {sessionCookie: cookie ?? undefined}) : Promise.reject(new ApiError('configuration_missing', 'API client is unavailable')), retry: false}); }
export function useSubmitReadingAnswers(client: ApiClient | null, cookie?: string | null, id?: number): UseMutationResult<ReadingAnswerResult, ApiError, number[]> { const qc = useQueryClient(); return useMutation({mutationFn: (answers) => client && id ? client.submitReadingAnswers(id, answers, {sessionCookie: cookie ?? undefined}) : Promise.reject(new ApiError('request_rejected', 'Reading session is unavailable')), onSuccess: () => { void qc.invalidateQueries({queryKey: ['reading', 'sessions']}); }, retry: false}); }
export function useContextualDictionary(client: ApiClient | null, cookie?: string | null): UseMutationResult<DictionaryResult, ApiError, DictionaryInput> { return useMutation({mutationFn: (input) => client ? client.contextualDictionary(input, {sessionCookie: cookie ?? undefined}) : Promise.reject(new ApiError('configuration_missing', 'API client is unavailable')), retry: false}); }
export function useLibraryVocabulary(client: ApiClient | null, cookie?: string | null): UseQueryResult<Awaited<ReturnType<ApiClient['listLibraryVocabulary']>>, ApiError> { return useQuery({queryKey: ['library', 'vocabulary'], queryFn: ({signal}) => client ? client.listLibraryVocabulary({signal, sessionCookie: cookie ?? undefined}) : Promise.reject(new ApiError('configuration_missing', 'API client is unavailable')), enabled: enabled(client, cookie), retry: false, staleTime: 0}); }
export function useSaveLibraryVocabulary(client: ApiClient | null, cookie?: string | null): UseMutationResult<Awaited<ReturnType<ApiClient['saveLibraryVocabulary']>>, ApiError, Parameters<ApiClient['saveLibraryVocabulary']>[0]> { const qc = useQueryClient(); return useMutation({mutationFn: (input) => client ? client.saveLibraryVocabulary(input, {sessionCookie: cookie ?? undefined}) : Promise.reject(new ApiError('configuration_missing', 'API client is unavailable')), onSuccess: () => { void qc.invalidateQueries({queryKey: ['library', 'vocabulary']}); }, retry: false}); }
export function useReviewLibraryVocabulary(client: ApiClient | null, cookie?: string | null): UseMutationResult<Record<string, unknown>, ApiError, {word: string; result: 'again' | 'got_it'}> { const qc = useQueryClient(); return useMutation({mutationFn: ({word, result}) => client ? client.reviewLibraryVocabulary(word, result, {sessionCookie: cookie ?? undefined}) : Promise.reject(new ApiError('configuration_missing', 'API client is unavailable')), onSuccess: () => { void qc.invalidateQueries({queryKey: ['library', 'vocabulary']}); void qc.invalidateQueries({queryKey: ['dashboard']}); }, retry: false}); }
