import {useMemo, useState, type ReactNode} from 'react';
import {Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {useRouter} from 'expo-router';
import {createConfiguredApiClient} from '../../src/api/client';
import {useSession} from '../../src/auth/SessionHarness';
import {useI18n} from '../../src/i18n/I18nProvider';
import {useTheme} from '../../src/theme/ThemeProvider';
import {CONTENT_MAX} from '../../src/theme/layout';
import {useGrammarLibrary, useGrammarLesson, useCompleteGrammarLesson} from '../../src/query/useGrammar';
import {useGrammarPractice} from '../../src/query/useWritingEvaluation';
import {setGrammarWritingHandoff} from '../../src/features/writing/writingHandoff';

export default function GrammarScreen() {
  const {t} = useI18n(); const {tokens} = useTheme(); const {sessionCookie} = useSession(); const router = useRouter();
  const client = useMemo(() => { try { return createConfiguredApiClient(); } catch { return null; } }, []);
  const library = useGrammarLibrary(client, sessionCookie); const [selectedId, setSelectedId] = useState(''); const id = selectedId || library.data?.lessons[0]?.id || '';
  const detail = useGrammarLesson(client, sessionCookie, id); const practice = useGrammarPractice(client, sessionCookie); const complete = useCompleteGrammarLesson(client, sessionCookie);
  const shell = (body: ReactNode) => <View style={[styles.container, {backgroundColor: tokens.colors.background}]}><Text accessibilityRole="header" style={[styles.title, {color: tokens.colors.heading}]}>{t('grammar.title')}</Text>{body}<Pressable accessibilityRole="button" onPress={() => router.replace('/(app)')} style={[styles.button, {backgroundColor: tokens.colors.accent}]}><Text style={[styles.buttonText, {color: tokens.colors.onAccent}]}>{t('nav.back_home' as never)}</Text></Pressable></View>;
  // Not signed in is a different fact from the service being unavailable.
  if (!sessionCookie) return shell(<Text style={{color: tokens.colors.mutedText}}>{t('grammar.signed_out' as never)}</Text>);
  if (!client || library.isError) return shell(<Text accessibilityRole="alert" style={{color: tokens.colors.danger}}>{t('grammar.unavailable')}</Text>);
  if (library.isPending) return <View style={[styles.container, {backgroundColor: tokens.colors.background}]}><Text style={{color: tokens.colors.text}}>{t('grammar.loading')}</Text></View>;
  if (!library.data?.lessons.length) return <View style={[styles.container, {backgroundColor: tokens.colors.background}]}><Text accessibilityRole="header" style={[styles.title, {color: tokens.colors.heading}]}>{t('grammar.title')}</Text><Text style={{color: tokens.colors.mutedText}}>{t('grammar.empty')}</Text></View>;
  const lesson = detail.data; const startPractice = () => { if (!id) return; practice.mutate({grammarId: id, evidence: ''}, {onSuccess: (task) => { setGrammarWritingHandoff(task, library.data?.language ?? 'en'); router.push('/(app)/writing'); }}); };
  return <ScrollView style={{flex: 1, backgroundColor: tokens.colors.background}} contentContainerStyle={[styles.container, {backgroundColor: tokens.colors.background}]}><Text accessibilityRole="header" style={[styles.title, {color: tokens.colors.heading}]}>{t('grammar.title')}</Text><Text style={{color: tokens.colors.mutedText}}>{t('grammar.select')}</Text><View style={styles.list}>{library.data.lessons.map((item) => <Pressable key={item.id} accessibilityRole="radio" accessibilityState={{selected: item.id === id}} onPress={() => setSelectedId(item.id)} style={[styles.choice, {borderColor: item.id === id ? tokens.colors.accent : tokens.colors.mutedText, backgroundColor: item.id === id ? tokens.colors.surface : 'transparent'}]}><Text style={{color: tokens.colors.text, fontWeight: item.id === id ? '700' : '400'}}>{item.title}</Text><Text style={{color: tokens.colors.mutedText}}>{item.level}{item.completed ? ' · ✓' : ''}</Text></Pressable>)}</View>{detail.isPending && <Text style={{color: tokens.colors.mutedText}}>{t('grammar.detail_loading')}</Text>}{detail.isError && <Text accessibilityRole="alert" style={{color: tokens.colors.danger}}>{t('grammar.detail_failed')}</Text>}{lesson && <View style={[styles.card, {backgroundColor: tokens.colors.surface, borderColor: tokens.colors.border}]}><Text style={{color: tokens.colors.text, fontWeight: '700'}}>{lesson.title}</Text>{lesson.quick_reference && <Text style={{color: tokens.colors.text}}>{JSON.stringify(lesson.quick_reference)}</Text>}{lesson.examples?.slice(0, 3).map((example, index) => <Text key={index} style={{color: tokens.colors.mutedText}}>{String(example.target ?? example.en ?? '')}</Text>)}<Pressable accessibilityRole="button" disabled={practice.isPending} onPress={startPractice} style={[styles.button, {backgroundColor: tokens.colors.accent, opacity: practice.isPending ? 0.6 : 1}]}><Text style={[styles.buttonText, {color: tokens.colors.onAccent}]}>{practice.isPending ? t('grammar.detail_loading') : t('grammar.practice')}</Text></Pressable><Pressable accessibilityRole="button" disabled={complete.isPending || lesson.completed} onPress={() => complete.mutate(id)} style={[styles.button, {borderColor: tokens.colors.accent, borderWidth: 1, opacity: lesson.completed ? 0.6 : 1}]}><Text style={{color: tokens.colors.accent}}>{complete.isPending ? t('grammar.completing') : lesson.completed ? t('grammar.completed') : t('grammar.complete')}</Text></Pressable></View>}{practice.isError && <Text accessibilityRole="alert" style={{color: tokens.colors.danger}}>{t('grammar.unavailable')}</Text>}{complete.isError && <Text accessibilityRole="alert" style={{color: tokens.colors.danger}}>{t('grammar.unavailable')}</Text>}</ScrollView>;
}
const styles = StyleSheet.create({container: {flexGrow: 1, padding: 24, gap: 12, width: '100%', maxWidth: CONTENT_MAX, alignSelf: 'center'}, title: {fontSize: 28, fontWeight: '700'}, list: {gap: 8}, choice: {padding: 14, borderRadius: 10, borderWidth: 1, gap: 4}, card: {padding: 16, borderRadius: 18, gap: 10, borderWidth: 1}, button: {padding: 14, borderRadius: 10, alignItems: 'center', minHeight: 44, justifyContent: 'center'}, buttonText: {fontSize: 14, fontWeight: '700'}});
