import assert from 'node:assert/strict';
import fs from 'node:fs';

const app=fs.readFileSync('app.py','utf8');
const admin=fs.readFileSync('static/admin.js','utf8');
const template=fs.readFileSync('templates/index.html','utf8');
const api=fs.readFileSync('writing_coach/product_activity_api.py','utf8');
const aggregate=fs.readFileSync('writing_coach/product_activity.py','utf8');
const telemetry=fs.readFileSync('writing_coach/ai/base.py','utf8');
const platformRepository=fs.readFileSync('writing_coach/persistence/platform_repository.py','utf8');
assert.match(app,/@app\.get\("\/api\/admin\/product-activity"/);
assert.match(app,/def admin_product_activity\(request: Request/);
assert.match(app,/def admin_product_activity\(request: Request/);
assert.match(app,/def admin_product_activity[\s\S]{0,500}product_activity_response\(request, _specialized_learning_repository, require_admin/);
assert.match(app,/operations_loader=lambda: admin_ai_operations\(request, limit=500\)/);
assert.match(fs.readFileSync('writing_coach/ai/control_plane.py','utf8'),/sample_truncated/);
assert.match(telemetry,/operator_test|configuration/);
assert.match(fs.readFileSync('writing_coach/ai/platform.py','utf8'),/origin": "learner"/);
assert.match(platformRepository,/action="ai\.operation"/);
assert.match(platformRepository,/payload=safe/);
assert.match(api,/cohort_since = since - timedelta\(days=7\)/);
assert.match(api,/cohort_start=cohort_since/);
assert.match(api,/aggregate_learner_impact_failures/);
assert.match(aggregate,/funnel_key/);
assert.match(aggregate,/funnel_keys\[skill\]\[funnel_stage\]\.add/);
assert.match(aggregate,/aggregate_learner_impact_failures/);
assert.match(aggregate,/origin.*learner/);
assert.match(aggregate,/sample_truncated/);
assert.match(admin,/fetch\('\/api\/admin\/product-activity\?window_days=7'/);
assert.match(admin,/adminProductActivity/);
assert.match(admin,/Daily activity\/completions/);
assert.match(admin,/return_windows/);
assert.match(admin,/returning_learners/);
assert.match(admin,/repeat_practice_learners/);
assert.match(admin,/daily_returning/);
assert.match(admin,/funnel/);
assert.match(admin,/cost_per_active_learner/);
assert.match(admin,/learner_impact_failures/);
assert.match(admin,/Learner-impact failure trends/);
assert.match(admin,/no unit-cost claim/);
assert.match(admin,/unavailable.*count|count.*unavailable/);
assert.match(template,/id="adminProductActivity"/);
assert.match(template,/No learner text, media URLs, or identifiers/);
assert.match(template,/repeat-practice returns/);
assert.match(template,/completion funnels/);
assert.match(template,/learner-impact failure trends/);
assert.doesNotMatch(admin,/event\.text|event\.media_url|event\.learner_id/);
console.log('Product activity Admin API/UI contract: PASS');
