import assert from 'node:assert/strict';
import fs from 'node:fs';

const app=fs.readFileSync('app.py','utf8');
const admin=fs.readFileSync('static/admin.js','utf8');
const template=fs.readFileSync('templates/index.html','utf8');
const api=fs.readFileSync('writing_coach/product_activity_api.py','utf8');
assert.match(app,/@app\.get\("\/api\/admin\/product-activity"/);
assert.match(app,/def admin_product_activity\(request: Request/);
assert.match(app,/def admin_product_activity\(request: Request/);
assert.match(app,/def admin_product_activity[\s\S]{0,500}product_activity_response\(request, _specialized_learning_repository, require_admin/);
assert.match(api,/cohort_since = since - timedelta\(days=7\)/);
assert.match(api,/cohort_start=cohort_since/);
assert.match(admin,/fetch\('\/api\/admin\/product-activity\?window_days=7'/);
assert.match(admin,/adminProductActivity/);
assert.match(admin,/Daily activity\/completions/);
assert.match(admin,/return_windows/);
assert.match(admin,/returning_learners/);
assert.match(admin,/repeat_practice_learners/);
assert.match(admin,/daily_returning/);
assert.match(template,/id="adminProductActivity"/);
assert.match(template,/No learner text, media URLs, or identifiers/);
assert.match(template,/repeat-practice returns/);
assert.doesNotMatch(admin,/event\.text|event\.media_url|event\.learner_id/);
console.log('Product activity Admin API/UI contract: PASS');
