import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync('app.py','utf8');
const module=fs.readFileSync('writing_coach/readiness_summary.py','utf8');
const admin=fs.readFileSync('static/admin.js','utf8');
const template=fs.readFileSync('templates/index.html','utf8');
assert.match(app,/\/api\/admin\/readiness-summary/);
assert.match(app,/require_admin\(request\)/);
assert.match(app,/build_readiness_summary/);
assert.match(module,/approval_state/);
assert.match(module,/runtime_activation/);
assert.match(module,/explicit_config_exists/);
assert.match(module,/server_configured/);
assert.match(module,/not_granted/);
assert.match(module,/no secrets, learner records, text, URLs, or event rows/);
assert.match(admin,/adminReadinessSummary/);
assert.match(admin,/fetch\('\/api\/admin\/readiness-summary/);
assert.match(admin,/not production-release approval/);
assert.match(template,/Operational readiness evidence/);
assert.doesNotMatch(module,/learner_key|event\.text|media_url/);
console.log('R17 readiness summary API/UI contract: PASS');
